import { StateData } from "@/types";

export const US_STATES: StateData[] = [
  { code: "AL", name: "Alabama", medianSalary: 52000, colFactor: 0.88, colLevel: "low" },
  { code: "AK", name: "Alaska", medianSalary: 72000, colFactor: 1.12, colLevel: "high" },
  { code: "AZ", name: "Arizona", medianSalary: 58000, colFactor: 1.02, colLevel: "medium" },
  { code: "AR", name: "Arkansas", medianSalary: 48000, colFactor: 0.85, colLevel: "low" },
  { code: "CA", name: "California", medianSalary: 75000, colFactor: 1.35, colLevel: "high" },
  { code: "CO", name: "Colorado", medianSalary: 65000, colFactor: 1.08, colLevel: "medium" },
  { code: "CT", name: "Connecticut", medianSalary: 70000, colFactor: 1.15, colLevel: "high" },
  { code: "DE", name: "Delaware", medianSalary: 60000, colFactor: 1.02, colLevel: "medium" },
  { code: "FL", name: "Florida", medianSalary: 55000, colFactor: 1.00, colLevel: "medium" },
  { code: "GA", name: "Georgia", medianSalary: 58000, colFactor: 0.95, colLevel: "low" },
  { code: "HI", name: "Hawaii", medianSalary: 65000, colFactor: 1.40, colLevel: "high" },
  { code: "ID", name: "Idaho", medianSalary: 52000, colFactor: 0.92, colLevel: "low" },
  { code: "IL", name: "Illinois", medianSalary: 62000, colFactor: 1.00, colLevel: "medium" },
  { code: "IN", name: "Indiana", medianSalary: 54000, colFactor: 0.90, colLevel: "low" },
  { code: "IA", name: "Iowa", medianSalary: 55000, colFactor: 0.88, colLevel: "low" },
  { code: "KS", name: "Kansas", medianSalary: 53000, colFactor: 0.89, colLevel: "low" },
  { code: "KY", name: "Kentucky", medianSalary: 50000, colFactor: 0.87, colLevel: "low" },
  { code: "LA", name: "Louisiana", medianSalary: 51000, colFactor: 0.90, colLevel: "low" },
  { code: "ME", name: "Maine", medianSalary: 55000, colFactor: 1.05, colLevel: "medium" },
  { code: "MD", name: "Maryland", medianSalary: 72000, colFactor: 1.18, colLevel: "high" },
  { code: "MA", name: "Massachusetts", medianSalary: 78000, colFactor: 1.30, colLevel: "high" },
  { code: "MI", name: "Michigan", medianSalary: 56000, colFactor: 0.92, colLevel: "low" },
  { code: "MN", name: "Minnesota", medianSalary: 64000, colFactor: 0.98, colLevel: "medium" },
  { code: "MS", name: "Mississippi", medianSalary: 45000, colFactor: 0.83, colLevel: "low" },
  { code: "MO", name: "Missouri", medianSalary: 54000, colFactor: 0.90, colLevel: "low" },
  { code: "MT", name: "Montana", medianSalary: 53000, colFactor: 0.95, colLevel: "low" },
  { code: "NE", name: "Nebraska", medianSalary: 55000, colFactor: 0.90, colLevel: "low" },
  { code: "NV", name: "Nevada", medianSalary: 56000, colFactor: 1.02, colLevel: "medium" },
  { code: "NH", name: "New Hampshire", medianSalary: 68000, colFactor: 1.10, colLevel: "high" },
  { code: "NJ", name: "New Jersey", medianSalary: 75000, colFactor: 1.22, colLevel: "high" },
  { code: "NM", name: "New Mexico", medianSalary: 51000, colFactor: 0.92, colLevel: "low" },
  { code: "NY", name: "New York", medianSalary: 70000, colFactor: 1.35, colLevel: "high" },
  { code: "NC", name: "North Carolina", medianSalary: 56000, colFactor: 0.95, colLevel: "low" },
  { code: "ND", name: "North Dakota", medianSalary: 58000, colFactor: 0.90, colLevel: "low" },
  { code: "OH", name: "Ohio", medianSalary: 55000, colFactor: 0.90, colLevel: "low" },
  { code: "OK", name: "Oklahoma", medianSalary: 50000, colFactor: 0.86, colLevel: "low" },
  { code: "OR", name: "Oregon", medianSalary: 60000, colFactor: 1.08, colLevel: "medium" },
  { code: "PA", name: "Pennsylvania", medianSalary: 58000, colFactor: 0.98, colLevel: "medium" },
  { code: "RI", name: "Rhode Island", medianSalary: 62000, colFactor: 1.08, colLevel: "medium" },
  { code: "SC", name: "South Carolina", medianSalary: 52000, colFactor: 0.92, colLevel: "low" },
  { code: "SD", name: "South Dakota", medianSalary: 53000, colFactor: 0.88, colLevel: "low" },
  { code: "TN", name: "Tennessee", medianSalary: 54000, colFactor: 0.90, colLevel: "low" },
  { code: "TX", name: "Texas", medianSalary: 59000, colFactor: 0.95, colLevel: "low" },
  { code: "UT", name: "Utah", medianSalary: 62000, colFactor: 1.02, colLevel: "medium" },
  { code: "VT", name: "Vermont", medianSalary: 57000, colFactor: 1.05, colLevel: "medium" },
  { code: "VA", name: "Virginia", medianSalary: 68000, colFactor: 1.08, colLevel: "medium" },
  { code: "WA", name: "Washington", medianSalary: 72000, colFactor: 1.15, colLevel: "high" },
  { code: "WV", name: "West Virginia", medianSalary: 47000, colFactor: 0.85, colLevel: "low" },
  { code: "WI", name: "Wisconsin", medianSalary: 56000, colFactor: 0.92, colLevel: "low" },
  { code: "WY", name: "Wyoming", medianSalary: 58000, colFactor: 0.95, colLevel: "low" },
  { code: "DC", name: "District of Columbia", medianSalary: 85000, colFactor: 1.45, colLevel: "high" },
];

export const US_MEDIAN_SALARY = 59000;
