import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AnalyticsScripts } from "@/components/Analytics";
import { SITE_URL, SITE_NAME } from "@/lib/site";

const defaultTitle = "Salary to Hourly Calculator | 18 Countries 2025";
const defaultDescription =
  "Free salary to hourly calculator for 18 countries. Convert annual salary to hourly rate with cost-of-living adjustments, state/province data, and freelance multipliers.";

export const metadata: Metadata = {
  title: {
    default: defaultTitle,
    template: "%s | Salary to Hourly",
  },
  description: defaultDescription,
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: defaultTitle,
    description: defaultDescription,
    // Next.js will serve the file generated by `app/opengraph-image.tsx`
    // at `/opengraph-image.png` — pointing here keeps OG and Twitter aligned.
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Salary to Hourly Calculator",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: defaultTitle,
    description: defaultDescription,
    images: ["/opengraph-image"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

// Next.js 15 prefers `viewport` as a separate export rather than metadata.themeColor.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#030712" },
  ],
};

const themeScript = `
  (function() {
    try {
      const theme = localStorage.getItem('theme');
      const isDark = theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches);
      if (isDark) document.documentElement.classList.add('dark');
    } catch (e) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <AnalyticsScripts />
      </head>
      <body className="flex min-h-screen flex-col bg-white font-sans text-gray-900 antialiased dark:bg-gray-950 dark:text-gray-100">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
