import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Breadcrumb from "@/components/Breadcrumb";
import JsonLd from "@/components/JsonLd";
import Link from "next/link";
import {
  getSalaryRange,
  validateSalaryForCountry,
  calculateBreakdownForCountry,
  listAllStaticSalaryParams,
} from "@/lib/salary-range";
import { getCountryById, COUNTRIES } from "@/data";
import { formatCurrency } from "@/lib/format";

// Force 404 for any (country, salary) pair not generated by `generateStaticParams`.
// Without this, /us/salary/0/hourly, /us/salary/abc/hourly, /xx/salary/75000/hourly
// would all render as thin pages with junk content.
export const dynamicParams = false;

export function generateStaticParams() {
  return listAllStaticSalaryParams();
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ country: string; amount: string }>;
}): Promise<Metadata> {
  const { country: countryId, amount } = await params;
  const country = getCountryById(countryId);
  const salary = Number(amount);
  if (validateSalaryForCountry(countryId, salary) === null) {
    return {};
  }

  const breakdown = calculateBreakdownForCountry(salary, country.annualHours);
  const k = salaryKLabel(salary, country);
  const hourlyLabel = formatCurrency(breakdown.hourly, country, 2);

  return {
    title: `${k} Salary to Hourly in ${country.name} – ${hourlyLabel}/hr`,
    description: `A ${k} salary in ${country.name} equals approximately ${hourlyLabel} per hour. Free breakdown into daily, weekly, and monthly pay using ${country.name}'s standard work hours.`,
    alternates: {
      canonical: `/${countryId}/salary/${salary}/hourly`,
    },
    openGraph: {
      title: `${k} Salary to Hourly in ${country.name}`,
      description: `Convert ${k} to an hourly rate in ${country.name}: ${hourlyLabel}/hour.`,
      url: `/${countryId}/salary/${salary}/hourly`,
    },
  };
}

function salaryKLabel(salary: number, country: { locale: string }): string {
  // Compact thousands with the country locale (e.g. "75K" for en-US,
  // "75 000" for fr-FR, "75,000" for ja-JP).
  const formatter = new Intl.NumberFormat(country.locale, {
    maximumFractionDigits: 0,
  });
  return `${formatter.format(salary / 1000)}K`;
}

export default async function SalaryPage({
  params,
}: {
  params: Promise<{ country: string; amount: string }>;
}) {
  const { country: countryId, amount } = await params;
  const country = getCountryById(countryId);
  const salary = Number(amount);

  if (validateSalaryForCountry(countryId, salary) === null) {
    notFound();
  }

  const breakdown = calculateBreakdownForCountry(salary, country.annualHours);
  const k = salaryKLabel(salary, country);
  const hourlyLabel = formatCurrency(breakdown.hourly, country, 2);
  const monthlyLabel = formatCurrency(breakdown.monthly, country);
  const annualLabel = formatCurrency(breakdown.annual, country);

  const range = getSalaryRange(countryId);
  // Median benchmark: simple heuristic vs the country's national median.
  const ratio = salary / country.nationalMedianSalary;
  const goodSalaryLabel =
    ratio > 1.2
      ? "above"
      : ratio > 0.9
        ? "around"
        : "below";

  const faqs = [
    {
      question: `What is ${k} a year hourly in ${country.name}?`,
      answer: `At ${country.weeklyHours} hours per week and 52 weeks per year, a ${k} salary in ${country.name} equals approximately ${hourlyLabel} per hour before taxes.`,
    },
    {
      question: `How much is ${k} a year after taxes in ${country.name}?`,
      answer: `After-tax income varies by ${country.name === "United States" ? "state and filing status" : "region and personal situation"}. As a rough estimate, ${k} may yield around 75–82% take-home annually.`,
    },
    {
      question: `Is ${k} a good salary in ${country.name}?`,
      answer: `${k} is ${goodSalaryLabel} the ${country.name} national median of ${formatCurrency(country.nationalMedianSalary, country)}. Actual comfort depends on your location and cost of living.`,
    },
    {
      question: `What is ${k} per month in ${country.name}?`,
      answer: `${k} divided by 12 months equals ${monthlyLabel} per month before taxes.`,
    },
  ];

  const schema = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        name: `${k} Salary to Hourly in ${country.name}`,
        description: `${k} a year in ${country.name} equals ${hourlyLabel} per hour.`,
        url: `/${countryId}/salary/${salary}/hourly`,
      },
      {
        "@type": "FAQPage",
        mainEntity: faqs.map((f) => ({
          "@type": "Question",
          name: f.question,
          acceptedAnswer: {
            "@type": "Answer",
            text: f.answer,
          },
        })),
      },
    ],
  };

  // Related salaries within ±2 steps of the requested amount.
  const relatedSalaries: number[] = [];
  for (
    let s = Math.max(range.min, salary - range.step * 2);
    s <= Math.min(range.max, salary + range.step * 2);
    s += range.step
  ) {
    if (s !== salary) relatedSalaries.push(s);
  }

  return (
    <>
      <JsonLd data={schema} />
      <Breadcrumb
        items={[
          { label: "Home", href: "/" },
          { label: country.name, href: `/?country=${countryId}` },
          { label: "Salary to Hourly", href: "/" },
          { label: k },
        ]}
      />

      <div className="mx-auto max-w-2xl space-y-8 px-4 py-8">
        {/* Hero / Answer-first */}
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">
            What Is a {k} Salary Per Hour in {country.name}?
          </h1>
          <div className="mx-auto max-w-md rounded-2xl border border-blue-200 bg-blue-50 p-5 dark:border-blue-800 dark:bg-blue-900/20">
            <div className="text-2xl font-bold text-blue-900 dark:text-blue-100">
              {k}/year = {hourlyLabel}/hour
            </div>
            <div className="mt-1 text-sm text-blue-700 dark:text-blue-300">
              Based on a {country.weeklyHours}-hour work week ({country.annualHours.toLocaleString(country.locale)} hours/year)
            </div>
          </div>
        </div>

        {/* Breakdown Table */}
        <section>
          <h2 className="mb-4 text-xl font-bold">{k} Salary Breakdown</h2>
          <div className="overflow-hidden rounded-2xl border border-gray-200 dark:border-gray-800">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 dark:bg-gray-900">
                <tr>
                  <th className="px-4 py-3 text-left font-semibold text-gray-700 dark:text-gray-300">
                    Period
                  </th>
                  <th className="px-4 py-3 text-right font-semibold text-gray-700 dark:text-gray-300">
                    Amount
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 dark:divide-gray-800">
                {[
                  { label: "Hourly", value: breakdown.hourly, highlight: true },
                  { label: "Daily (8 hrs)", value: breakdown.daily },
                  { label: "Weekly", value: breakdown.weekly },
                  { label: "Biweekly", value: breakdown.biweekly },
                  { label: "Monthly", value: breakdown.monthly },
                  { label: "Annual", value: breakdown.annual },
                ].map((row) => (
                  <tr
                    key={row.label}
                    className={
                      row.highlight
                        ? "bg-blue-50/50 dark:bg-blue-900/10"
                        : ""
                    }
                  >
                    <td className="px-4 py-3 text-gray-700 dark:text-gray-300">
                      {row.label}
                    </td>
                    <td
                      className={`px-4 py-3 text-right font-mono font-medium ${
                        row.highlight
                          ? "text-blue-700 dark:text-blue-300"
                          : "text-gray-900 dark:text-white"
                      }`}
                    >
                      {formatCurrency(row.value, country, row.highlight ? 2 : 0)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Formula */}
          <div className="mt-4 rounded-xl border border-gray-100 bg-gray-50 p-4 text-center text-sm text-gray-600 dark:border-gray-800 dark:bg-gray-900 dark:text-gray-400">
            <span className="font-mono">
              {k} ÷ {country.annualHours.toLocaleString(country.locale)} hours = {hourlyLabel}/hour
            </span>
          </div>
        </section>

        {/* Context Paragraph */}
        <section className="space-y-3 text-gray-600 dark:text-gray-400">
          <p>
            If you earn {k} per year in {country.name} and work a standard{" "}
            {country.weeklyHours}-hour week for 52 weeks, your hourly rate is
            approximately {hourlyLabel}. {annualLabel} a year sits {goodSalaryLabel}{" "}
            the {country.name} median income.
          </p>
        </section>

        {/* Assumptions */}
        <section className="rounded-2xl border border-gray-200 bg-gray-50 p-5 dark:border-gray-800 dark:bg-gray-900">
          <h3 className="mb-3 text-sm font-semibold text-gray-700 dark:text-gray-300">
            Assumptions
          </h3>
          <ul className="list-disc space-y-1.5 pl-5 text-xs text-gray-500 dark:text-gray-400">
            <li>
              52 working weeks per year; no unpaid leave subtracted.
            </li>
            <li>
              {country.weeklyHours} hours per week (standard full-time in {country.name}).
            </li>
            <li>
              Gross pay only — before taxes and any local social contributions.
            </li>
            <li>No overtime, bonuses, commissions, or tips included.</li>
          </ul>
        </section>

        {/* FAQ */}
        <section>
          <h2 className="mb-4 text-xl font-bold">
            Frequently Asked Questions
          </h2>
          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <div
                key={i}
                className="rounded-xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900"
              >
                <details className="group">
                  <summary className="flex cursor-pointer items-center justify-between px-5 py-4 text-sm font-medium text-gray-900 dark:text-white">
                    {faq.question}
                    <svg
                      className="h-4 w-4 shrink-0 text-gray-400 transition-transform group-open:rotate-180"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth={2}
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M19 9l-7 7-7-7"
                      />
                    </svg>
                  </summary>
                  <div className="border-t border-gray-100 px-5 py-4 text-sm text-gray-600 dark:border-gray-800 dark:text-gray-400">
                    {faq.answer}
                  </div>
                </details>
              </div>
            ))}
          </div>
        </section>

        {/* Related Salaries */}
        {relatedSalaries.length > 0 && (
          <section>
            <h2 className="mb-4 text-xl font-bold">
              Similar Salary Conversions
            </h2>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              {relatedSalaries.map((s) => {
                const h = calculateBreakdownForCountry(s, country.annualHours)
                  .hourly;
                return (
                  <Link
                    key={s}
                    href={`/${countryId}/salary/${s}/hourly`}
                    className="rounded-xl border border-gray-200 bg-white p-3 text-center transition hover:border-blue-300 hover:shadow-sm dark:border-gray-800 dark:bg-gray-900 dark:hover:border-blue-700"
                  >
                    <div className="text-sm font-medium text-gray-900 dark:text-white">
                      {salaryKLabel(s, country)} to hourly
                    </div>
                    <div className="mt-0.5 text-xs text-gray-500 dark:text-gray-400">
                      {formatCurrency(h, country, 2)}/hour
                    </div>
                  </Link>
                );
              })}
            </div>
          </section>
        )}

        {/* CTA back to calculator */}
        <div className="text-center">
          <Link
            href={`/?country=${countryId}&salary=${salary}`}
            className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-700"
          >
            Try the Full Calculator
            <svg
              width="16"
              height="16"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M5 12h14M12 5l7 7-7 7"
              />
            </svg>
          </Link>
          <p className="mt-2 text-xs text-gray-400 dark:text-gray-500">
            Compare across {COUNTRIES.length} countries with cost-of-living adjustments.
          </p>
        </div>
      </div>
    </>
  );
}